### ISSUE TITLE
[K8SPS-18] MySQL Operator with asynchronous replication - initial version

### ISSUE THREAD

**Issue by spron-in** [percona/roadmap#20]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about the feature**
Create MySQL operator with regular asynchronous replication.
PXC is great, but sync replication brings additional overhead and might not be required for an application.
It might be just additional flag in existing PXC Operator that would disable Galera.

**Which product(s) is this request for?**
MySQL, Operators

**Tell us about the problem**
Remove PXC overhead and run regular MySQL async replication

**Describe alternatives you've considered**
Other operators

**Additional context**
Anything else that you think might be useful

**Comment by bratao** [comment]
This would also enable the usage of Myrocks! For some scenarios, this would be awesome!
