### ISSUE TITLE
[K8SPSMDB-432] Add support for cluster-wide mode in PSMDB Operator

### ISSUE THREAD

**Issue by spron-in** [percona/roadmap#28]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about the feature**
Cluster-wide mode support for PSMDB Operator. It should allow users to run one Operator and control multiple Percona Server for MongoDB clusters in different namespaces. There is such feature for PXC Operator already.

**Which product(s) is this request for?**
MongoDB, Operators

**Tell us about the problem**
Run namespace isolated clusters with one Operator.

**Describe alternatives you've considered**
Run an Operator per namespace

**Additional context**
None

**Comment by dalbani** [comment]
Isn't it simply a question of setting `WATCH_NAMESPACE` environment variable to an empty string, in addition to setting the permissions with `ClusterRole`s (via the Helm chart)??
I read that the PXC Operator already supports it. What had to be done technically to make it happen?

**Comment by jconradhanson** [comment]
@spron-in @tplavcic Is there an updated timeline regarding cluster-wide support by the PSMDB Operator? 

According to [this issue comment](https://github.com/percona/percona-helm-charts/pull/122#issuecomment-1113273331), support would be considered after release `1.12.0`, which we are now on `1.12.1` as of June 10th, 2022 (two months ago at time of this comment). 

There are already two PRs open that address this issue on the [PSMDB Operator's helm chart](https://github.com/percona/percona-helm-charts/tree/main/charts/psmdb-operator). 
1. percona/percona-helm-charts[#122](https://github.com/percona/percona-helm-charts/pull/122)
2. percona/percona-helm-charts[#125](https://github.com/percona/percona-helm-charts/pull/125)

FYI I'm willing to help with what will push this over the finish line.

**Comment by tplavcic** [comment]
@jconradhanson Cluster wide support in PSMDB operator is scheduled to be released in `1.13.0`.
Ticket is located here: https://jira.percona.com/browse/K8SPSMDB-203
Helm charts usually get updated several days after operator release.

**Comment by spron-in** [comment]
Duplicate
