### ISSUE TITLE
[K8SPXC-1005] Add support of Microsoft Azure Blob storage for the backups

### ISSUE THREAD

**Issue by spron-in** [percona/roadmap#81]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about the feature**

Hi,

Starting from 8.0.27-19 Percona XtraBackup  supports Microsoft Azure Blob storage.
We need to add support of Azure storage to operator too. How to use it percona.com/doc/percona-xtrabackup/8.0/xbcloud/xbcloud_azure.html

[Link to JIRA](https://jira.percona.com/browse/K8SPXC-1005)

**Comment by qdupuy** [comment]
🖖 

Do you have an expected delivery date for this feature?
