### ISSUE TITLE
[K8SPSMDB-793] Add ability to set annotations and labels for PVCs

### ISSUE THREAD

**Issue by spron-in** [percona/roadmap#82]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about the feature**

Based on [https://forums.percona.com/t/setting-custom-annotations-for-pvc/17625]

 

Right now it is not possible to add annotations to PVCs created by the Operator.

The proposal is to add labels and annotations sections to volumeSpecs - replica sets and config server replica sets.
{code:java}
volumeSpec:
  annotations: {}
  labels: {}
  ... {code}
 

[Link to JIRA](https://jira.percona.com/browse/K8SPSMDB-793)

**Comment by Danielss89** [comment]
I need the same for the mysql operator :)
