### ISSUE TITLE
[K8SPG-300] General Availability - Percona Operator for PostgreSQL v2

### ISSUE THREAD

**Issue by spron-in** [percona/roadmap#91]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about the feature**

This is an epic to capture and track all the tasks that we need to deliver to promote PG Operator v2 to General Availability. 

 

The top focus:
 - End-to-end test coverage
 - Documentation
 - Custom resource structure and variables

[Link to JIRA](https://jira.percona.com/browse/K8SPG-300)

**Comment by hedgss** [comment]
When will it be available on [https://operatorhub.io](https://operatorhub.io/operator/percona-postgresql-operator) ?
