### ISSUE TITLE
Helm values for mongo db helm charts should allow override of individual replicaset configurations ,like size ,requests, limits etc

### ISSUE THREAD

**Issue by Padmabishek** [percona/roadmap#98]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about the feature**
Current helm values file for mongo db uses array structure for configuring replica sets . This will be difficult to override using the helm --set option as it will override the entire array options .Please refer the recommended way i.e, using maps [here](https://helm.sh/docs/chart_best_practices/values/#:~:text=For%20this%20reason%2C%20it%27s%20often%20better%20to%20structure%20your%20values%20file%20using%20maps.).  Helm charts should allow override of individual replica set configurations.
current configuration for replsets is as below
replsets:
  - name: rs0
    size: 3
    affinity:
      affinityEnabled: true
      advanced:
        nodeAffinity:
          reqdForSchIgnForExec:
            nodeSelTerms:
              matchExpr:

It can be made 
replsets:
  rs0:
    size: 3
    affinity:
      affinityEnabled: true
      advanced:
        nodeAffinity:
          reqdForSchIgnForExec:
            nodeSelTerms:
              matchExpr:
This will be very useful in overriding default configurations in helm using deployment tools like porter 
**Which product(s) is this request for?**
MongoDB

**Tell us about the problem**
Its difficult to override replicaset configurations like limits and requests and size , we may have to pass the entire array for setting using -- set.  Helm charts should allow override of individual replica set configurations.

**Describe alternatives you've considered**
Passing entire array using --set

**Additional context**
Anything else that you think might be useful

**Comment by spron-in** [comment]
Hello @Padmabishek , thank you for submitting it.
It seems this should rather land in percona-helm-chart [issues](https://github.com/percona/percona-helm-charts/issues) or in our [JIRA](https://jira.percona.com/browse/K8SPSMDB), but not in the roadmap.
